<?php

namespace AppBundle\Repository;

/**
 * AudienciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudienciasRepository extends \Doctrine\ORM\EntityRepository
{
}
