nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: []
            max_age: 36000
            hosts: []
            origin_regex: false
            
        paths:
            '^/api/':
                allow_origin: ['http://localhost:8080']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600